
pub const WBEM_FLAG_ALWAYS: i32 = 0;
pub const WBEM_FLAG_ONLY_IF_TRUE: i32 = 0x1;
pub const WBEM_FLAG_ONLY_IF_FALSE: i32 = 0x2;
pub const WBEM_FLAG_ONLY_IF_IDENTICAL: i32 = 0x3;
pub const WBEM_MASK_PRIMARY_CONDITION: i32 = 0x3;
pub const WBEM_FLAG_KEYS_ONLY: i32 = 0x4;
pub const WBEM_FLAG_REFS_ONLY: i32 = 0x8;
pub const WBEM_FLAG_LOCAL_ONLY: i32 = 0x10;
pub const WBEM_FLAG_PROPAGATED_ONLY: i32 = 0x20;
pub const WBEM_FLAG_SYSTEM_ONLY: i32 = 0x30;
pub const WBEM_FLAG_NONSYSTEM_ONLY: i32 = 0x40;
pub const WBEM_MASK_CONDITION_ORIGIN: i32 = 0x70;
pub const WBEM_FLAG_CLASS_OVERRIDES_ONLY: i32 = 0x100;
pub const WBEM_FLAG_CLASS_LOCAL_AND_OVERRIDES: i32 = 0x200;
pub const WBEM_MASK_CLASS_CONDITION: i32 = 0x30;
